// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXUWCKrqb6lyXaV2BCiDVlcVh8TpXIOOk',
    appId: '1:505112648654:web:d248c8468beba2fd2d699f',
    messagingSenderId: '505112648654',
    projectId: 'fyp2024-59377',
    authDomain: 'fyp2024-59377.firebaseapp.com',
    storageBucket: 'fyp2024-59377.appspot.com',
    measurementId: 'G-BL01YFPJ90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-2mUcjDQBCckg4jovykRFTBjr6o9RvTE',
    appId: '1:505112648654:android:07f0f7ef5ecacb842d699f',
    messagingSenderId: '505112648654',
    projectId: 'fyp2024-59377',
    storageBucket: 'fyp2024-59377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD29VBPEKA8aGqObEnyalP1kmXYb3Ou88A',
    appId: '1:505112648654:ios:749c00d6f90878702d699f',
    messagingSenderId: '505112648654',
    projectId: 'fyp2024-59377',
    storageBucket: 'fyp2024-59377.appspot.com',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD29VBPEKA8aGqObEnyalP1kmXYb3Ou88A',
    appId: '1:505112648654:ios:73a7d0b8c3c489f52d699f',
    messagingSenderId: '505112648654',
    projectId: 'fyp2024-59377',
    storageBucket: 'fyp2024-59377.appspot.com',
    iosBundleId: 'com.example.fypApp.RunnerTests',
  );
}
